#include<stdio.h>
int main()
{
    int i, j, k;
    for(i=1;i<=3;i++)
    {
        for(j=1;j<=18;j++)
        {
            printf("*");
        }
        printf("\n");
    }
    for(i=1;i<=3;i++)
    {
      for(j=1;j<=4;j++)
        {
            printf("*");
        }
        printf("\n");
    }
    for(i=1;i<=3;i++)
    {
     for(j=1;j<=18;j++)
        {
            printf("*");
        }
        printf("\n");
    }
    for(i=1;i<=3;i++)
    {
      for(j=1;j<=14;j++)
        {
            printf(" ");
        }
      for(j=1;j<=4;j++)
        {
            printf("*");
        }
        printf("\n");
    }
     for(i=1;i<=3;i++)
    {
      for(j=1;j<=18;j++)
        {
            printf("*");
        }
        printf("\n");
    }
}
